#!/usr/bin/env bash

function set_github_url() {
    local url=$1
    git remote set-url origin $url
}

function decrypt_key() {
    local file=$1
    local dest="$2/$file"

    if [ -f $dest ]; then
        exit 0
    fi

    gpg -o $dest -d $file
}

gh_pat=$(gpg -d $(pwd)/vars/gh-pat 2> /dev/null)

secrets_dir="$HOME/github/secret-sauce"
if [ ! -d $secrets_dir ]; then
    git clone "https://oauth2:$gh_pat@github.com/dnlznk/secret-sauce" $secrets_dir
    set_github_url "git@github.com:dnlznk/secret-sauce"
    cd $secrets_dir
else
    cd $secrets_dir
    git pull
fi


ssh_dir="$HOME/.ssh"
decrypt_key "config" "$ssh_dir"
decrypt_key "github" "$ssh_dir"
decrypt_key "github.pub" "$ssh_dir"
decrypt_key "og-gitlab" "$ssh_dir"
decrypt_key "og-gitlab.pub" "$ssh_dir"
decrypt_key "private.gpg" "$HOME"
decrypt_key "public.gpg" "$HOME"

gpg --import "$HOME/private.gpg"
gpg --import "$HOME/public.gpg"

echo "dnlznk:5" > gpg --import-ownertrust

rm -f "$HOME/private.gpg" "$HOME/public.gpg"

cd -

dotfiles_dir="$HOME/.dotfiles"
if [[ -d "$dotfiles_dir" ]]; then
    exit 0
fi

git clone https://github.com/dnlznk/dotfiles $dotfiles_dir
cd $dotfiles_dir
set_github_url "git@github.com:dnlznk/dotfiles"

fdfind -H ".bash|.profile" -x rm

./linux

sudo mkdir -p /usr/share/backgrounds
sudo cp wallpaper/tropical-beach.png /usr/share/backgrounds/tropical-beach.png

source "$HOME/.bashrc"

cd -

git clone git@github.com:dnlznk/pass-store $PASSWORD_STORE_DIR
git clone git@github.com:dnlznk/notes $NOTES_DIR
