#!/usr/bin/env bash

sudo apt update && sudo apt upgrade -y

github_dir="$HOME/github"
if [[ ! -d "$github_dir" ]]; then
    mkdir -p "$github_dir"
fi

# TODO add tldr client in rust install
packages=(
    tmux
    stow
    gcc
    valgrind
    build-essential
    gawk
    fd-find
    ripgrep
    ninja-build
    gettext
    cmake
    unzip
    curl
    gpg
    keychain
    openssh-client
    mokutil
    pass
    ufw
    dkms
    fswatch
    ntfs-3g
    fuse3
    fwupd
    luarocks
    ffmpeg
    vlc
    mpv
    bc
    genisoimage
    network-manager
    xdotool
    libsecret-1-dev
    jq
    libcunit1-dev
    sqlite3
    libsqlite3-dev
    libimlib2-dev
    libxcb-util-dev
    acpid
    lm-sensors
    iw
)

sudo apt install -y "${packages[@]}"

# Activate firewall
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable

# Activate ssh agent
systemctl --user enable ssh-agent.socket
systemctl --user start ssh-agent.socket

sudo loginctl enable-linger $USER
